import esbuild from "esbuild";
import { readFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";

// Read manifest to get version
const manifest = JSON.parse(readFileSync("./manifest.json", "utf8"));

esbuild
  .build({
    banner: {
      js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@electron/remote",
      "@codemirror/*",
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
    platform: "node",
    define: {
      "process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
    },
  })
  .catch(() => process.exit(1));
